title: Topics in Le Cam's Asymptotic Theory of Statistical Experiments
email: edgarcia@est-econ.uc3m.es
description: > # this means to ignore newlines until "baseurl:"
  TODO.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://egarpor.github.io/lecam" # the base hostname & protocol for your site
github_username: egarpor

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
show_downloads: false
google_analytics: UA-91505318-1